
name: Npm Publish
on:
  workflow_dispatch:
jobs:
  publish:
    name: Build, bump & publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --frozen-lockfile

      # - run: yarn run test
      - run: yarn run build

      # new release
      - name: Bump version & publish
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "648384410li@gmail.com"

          yarn version --patch

      #     git push && git push --tags

      # to npm
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
